---
extends: default

rules:
  # 80 chars should be enough, but don't fail if a line is longer
  line-length:
    max: 80
    level: warning

  # don't worry about EOL for now
  new-line-at-end-of-file: disable

ignore: |
  .github/workflows/
  devenv.yaml
  devenv.lock
