name: CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: cachix/install-nix-action@v23
        with:
          nix_path: nixpkgs=channel:nixpkgs-unstable
      - uses: cachix/cachix-action@v13
        with:
          name: devenv
      - name: Install devenv
        run: nix-env -if https://github.com/cachix/devenv/tarball/latest
      - name: Test build environment
        run: devenv test
