name: CI
on: [push, pull_request]

jobs:
  tests:
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: devenv shell bash -- -e {0}

    steps:
      - uses: actions/checkout@v4

      - uses: cachix/install-nix-action@v31
      - uses: cachix/cachix-action@v16
        with: { name: devenv }

      # Install devenv itself (must run in plain Bash!)
      - name: Install devenv
        shell: bash
        run: nix profile install nixpkgs#devenv

      - name: devenv test
        run: devenv test

      - name: Phoenix tests
        run: |
          mix do deps.get, ecto.create, ecto.migrate, test
