---
name: CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  test:
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest]
      fail-fast: false
    runs-on: ${{ matrix.os }}

    steps:
      - uses: actions/checkout@v4

      - uses: cachix/install-nix-action@v31
        with:
          nix_path: nixpkgs=channel:nixpkgs-unstable

      - uses: cachix/cachix-action@v16
        with:
          name: devenv

      - name: Install devenv
        run: nix-env -if https://github.com/cachix/devenv/tarball/latest

      - name: Test build environment
        run: devenv test

      # Start PostgreSQL from devenv
      - name: Start PostgreSQL from devenv
        run: devenv up &

      # Give PostgreSQL time to initialize
      - name: Wait for PostgreSQL processes to start
        shell: bash -e {0}
        run: |
          echo "Giving PostgreSQL time to initialize..."
          sleep 15
          echo "Checking if PostgreSQL is running:"
          ps aux | grep "[p]ostgres" || echo "No postgres processes found yet"

      # Wait for PostgreSQL
      - name: Wait for PostgreSQL
        shell: devenv shell bash -- -e {0}
        run: |
          # Print debugging information
          echo "User ID: $(id -u)"
          echo "Looking for PostgreSQL socket files:"
          find /run/user -name ".s.PGSQL.*" -ls 2>/dev/null || echo "No socket files found in /run/user"
          find /tmp -name ".s.PGSQL.*" -ls 2>/dev/null || echo "No socket files found in /tmp"

          echo "PostgreSQL data directories:"
          find /run/user -path "*/postgres" -type d -ls 2>/dev/null || echo "No postgres directories found"

          echo "PostgreSQL process info:"
          ps aux | grep "[p]ostgres" || echo "No postgres processes found"

          # Wait up to 120 seconds for PostgreSQL to be ready
          timeout=120

          # First try the auto-detection approach
          echo "Attempting to connect using socket directory detection..."
          until [ $timeout -le 0 ]
          do
            # Try to find the socket directory dynamically
            socket_dir=$(find /run/user -path "*/postgres" -type d 2>/dev/null | head -1)
            if [ -n "$socket_dir" ]; then
              echo "Trying connection with socket directory: $socket_dir"
              if pg_isready -h "$socket_dir" -U postgres; then
                echo "PostgreSQL is ready!"
                exit 0
              fi
            fi

            # Also try the default connection
            if pg_isready -U postgres; then
              echo "PostgreSQL is ready with default connection!"
              exit 0
            fi

            echo "Waiting for PostgreSQL to be ready... ($timeout seconds left)"
            sleep 2
            timeout=$((timeout-2))
          done

          echo "Timed out waiting for PostgreSQL"
          echo "Final debugging info:"
          find /run/user -name ".s.PGSQL.*" -ls 2>/dev/null || echo "No socket files found in /run/user"
          ps aux | grep postgres || echo "No postgres processes found"
          netstat -ltnp 2>/dev/null | grep postgres || echo "No postgres connections found"
          exit 1

      # Phoenix application tests - ensure HOME is set properly
      - name: Setup Phoenix environment
        shell: devenv shell bash -- -e {0}
        env:
          HOME: "/home/runner"
        run: |
          mix local.hex --force
          mix local.rebar --force

      - name: Install Phoenix dependencies
        shell: devenv shell bash -- -e {0}
        env:
          HOME: "/home/runner"
        run: mix deps.get

      - name: Compile Phoenix application
        shell: devenv shell bash -- -e {0}
        env:
          HOME: "/home/runner"
        run: mix compile --warnings-as-errors

      - name: Create and migrate test database
        shell: devenv shell bash -- -e {0}
        env:
          HOME: "/home/runner"
          MIX_ENV: test
        run: |
          mix ecto.create
          mix ecto.migrate

      - name: Run Phoenix tests
        shell: devenv shell bash -- -e {0}
        env:
          HOME: "/home/runner"
          MIX_ENV: test
        run: mix test
