---
name: CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  test:
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest]
      fail-fast: false
    runs-on: ${{ matrix.os }}

    steps:
      - uses: actions/checkout@v4

      - uses: cachix/install-nix-action@v31
        with:
          nix_path: nixpkgs=channel:nixpkgs-unstable

      - uses: cachix/cachix-action@v16
        with:
          name: devenv

      - name: Install devenv
        run: nix-env -if https://github.com/cachix/devenv/tarball/latest

      # Add step to set up DEVENV_HOME for macOS
      - name: Configure devenv for macOS
        if: runner.os == 'macOS'
        run: |
          mkdir -p ${HOME}/.local/state/devenv
          export DEVENV_HOME=${HOME}/.local/state/devenv
          echo "DEVENV_HOME=${HOME}/.local/state/devenv" >> $GITHUB_ENV

      - name: Test build environment
        run: devenv test

      - name: Start PostgreSQL and wait for it to be ready
        uses: JarvusInnovations/background-action@v1
        with:
          run: devenv up
          wait-on: |
            tcp:localhost:5432
          wait-for: 2m
          tail: true
          log-output: stderr,stdout
          log-output-if: failure

      - name: Verify PostgreSQL is ready
        shell: devenv shell bash -- -e {0}
        env:
          HOME: "/home/runner"
        run: check-postgres

      - name: Setup Phoenix environment
        shell: devenv shell bash -- -e {0}
        env:
          HOME: "/home/runner"
        run: |
          mix local.hex --force
          mix local.rebar --force

      - name: Install Phoenix dependencies
        shell: devenv shell bash -- -e {0}
        env:
          HOME: "/home/runner"
        run: mix deps.get

      - name: Compile Phoenix application
        shell: devenv shell bash -- -e {0}
        env:
          HOME: "/home/runner"
        run: mix compile --warnings-as-errors

      - name: Create and migrate test database
        shell: devenv shell bash -- -e {0}
        env:
          HOME: "/home/runner"
          MIX_ENV: test
        run: |
          mix ecto.create
          mix ecto.migrate

      - name: Run Phoenix tests
        shell: devenv shell bash -- -e {0}
        env:
          HOME: "/home/runner"
          MIX_ENV: test
        run: mix test
