---
name: CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  test:
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest]
      fail-fast: false
    runs-on: ${{ matrix.os }}
    defaults:
      run:
        shell: devenv shell bash -- -e {0}
    steps:
      - uses: actions/checkout@v4
      - uses: cachix/install-nix-action@v31
        with:
          nix_path: nixpkgs=channel:nixpkgs-unstable
      - uses: cachix/cachix-action@v16
        with:
          name: devenv
      - name: Install devenv
        shell: bash
        run: nix profile install nixpkgs#devenv
      - name: Test build environment
        run: devenv test
      - name: Start PostgreSQL and wait for it to be ready
        uses: JarvusInnovations/background-action@v1
        with:
          run: devenv up &
          wait-on: |
            tcp:localhost:5432
          wait-for: 2m
          tail: true
          log-output: stderr,stdout
          log-output-if: failure
      - name: Verify PostgreSQL is ready
        run: check-postgres
      - name: Setup Phoenix environment
        run: |
          mix local.hex --force
          mix local.rebar --force
      - name: Install Phoenix dependencies
        run: mix deps.get
      - name: Compile Phoenix application
        run: mix compile --warnings-as-errors
      - name: Create and migrate test database
        env:
          MIX_ENV: test
        run: |
          mix ecto.create
          mix ecto.migrate
      - name: Run Phoenix tests
        env:
          MIX_ENV: test
        run: mix test
