---
name: Format Check

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  format:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: cachix/install-nix-action@v23
        with:
          nix_path: nixpkgs=channel:nixpkgs-unstable

      - name: Check Nix formatting with nixpkgs-fmt
        run: |
          nix-shell -p nixpkgs-fmt --run "nixpkgs-fmt --check *.nix"

      - name: Check YAML formatting
        run: |
          nix-shell -p yamllint --run "yamllint -c .github/yamllint.yml ."
