---
name: Update dependencies

on:
  schedule:
    - cron: "0 0 * * 0" # Weekly on Sunday
  workflow_dispatch: # Allow manual triggering

jobs:
  update:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: cachix/install-nix-action@v23
        with:
          nix_path: nixpkgs=channel:nixpkgs-unstable
      - name: Install devenv
        run: nix-env -if https://github.com/cachix/devenv/tarball/latest
      - name: Update dependencies
        run: devenv update
      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v5
        with:
          commit-message: Update devenv dependencies
          title: Update devenv dependencies
          branch: update-dependencies
